# Generated by Django 5.1.5 on 2025-03-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Realtime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beacondevice',
            name='location',
        ),
        migrations.AddField(
            model_name='proximityevent',
            name='motion_detected',
            field=models.BooleanField(default=False),
        ),
    ]
